### ISSUE TITLE
Set Position / Scrubbing / Seeking

### ISSUE THREAD

**Issue by turbo** [AnthumChris/fetch-stream-audio#25]
How can I set the start position within the stream? For example, a user might want to click/seek to a given point in the streamed file and I want to set the player to that position to resume playback from that point (without the waiting for the whole file to load).

**Comment by AnthumChris** [comment]
Unfortunately, these playback demos do not provide examples for seeking.  You may also wish to see the conversation at https://github.com/AnthumChris/opus-stream-decoder/issues/1
