### ISSUE TITLE
Demo is broken - wrong wasm mimetype

### ISSUE THREAD

**Issue by Samuel-B-D** [AnthumChris/fetch-stream-audio#27]
The wasm in the demo is served with `content-type: application/wasm; charset=utf-8` which don't make sense and break the streaming compilation.
It should be served with the mimetype `application/wasm` (charset doesn't make sense for a binary format like wasm).

**Comment by AnthumChris** [comment]
On which browser/device are you seeing this error?  Could you provide any reproduction steps?
