### ISSUE TITLE
save opus packet to ogg container

### ISSUE THREAD

**Issue by vinnitu** [AnthumChris/fetch-stream-audio#35]
Hello!

I know it is off-topic. But it is related.

I have opus packets which is merged from 2 frames.
Size of packet can be great than 255 byte (max segment size in ogg page)
I can split this packet into two packets with single frame and save each in separated segment.

But... Can we simple split packet into parts\chunks 255 bytes + last part less then 255
ang put it in sequence segments into ogg page?

It doesnt work to me (maybe incorrect code). But I am interesting how to handle it properly? We really need to repack doubled packets to separated packet? or not?

Sorry for my bad english.

**Comment by AnthumChris** [comment]
Hey there. I apologize for not being able to answer, but I wanted to respond as quickly as possible. I would recommend StackOverflow for any questions relating Ogg that are not specific to the code in this repository

**Comment by vinnitu** [comment]
thank you
