### ISSUE TITLE
Stream audio output from PC

### ISSUE THREAD

**Issue by zzph** [AnthumChris/fetch-stream-audio#36]
Hi,

This project looks great. Forgive me if this is a basic question.

I want to enable streaming the audio output from my computer (Mac).  Latency isn't important.

WebRTC doesn't seem to cut it, as the quality isn't great.

Could I "stream" my audio to an opus/wav file? IE the file would continually be written to  

Do you have a suggestion on how it can be done in `fetch-stream-audio`?

Thanks,

**Comment by AnthumChris** [comment]
I apologize, but I'm not sure how to answer your question.  I would recommend StackOverflow to field opinions. Their community is great and extremely helpful.  I'm going to close this issue because it's not specific to this code repo.
