### ISSUE TITLE
Failed when size too large

### ISSUE THREAD

**Issue by KayacChang** [AnthumChris/fetch-stream-audio#8]
Excuse me, 
I'm try too load a big wav music, 
but some problem happened like noise and stop play .
And I try the mp3 format but it doesn't work.

**Comment by egg734631** [comment]
Thank you, I got it.
I try 50MB music, 5 mins song.

**Comment by AnthumChris** [comment]
For large files, [Media Source Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) is recommended
